### ISSUE TITLE
reduce traffic

### ISSUE THREAD

**Issue by hypnagonia** [harmony-one/explorer-v2-frontend#118]
currently a tab with explorer open generates significant amount of unnecessary traffic
stop all polling (erc20 updates, $ rates etc) when tab is not active. enable when it is active again

**Comment by victaphu** [comment]
Step 1: 
To reduce impact of solution on existing code, I plan to keep all the timeouts and timers that are running in the code; however when the page loses focus then those timers will not trigger any costly updates.

Step 2: 
Pause any streams coming from the websockets when we tab away. This is more involved because there will be a lag in the data sync once we re-focus. If Step 1 is sufficient we can forgo this step as its more tedious. For this approach we would stop the stream after a certain elapsed time when no focus occurs (e.g. after 1 minute)

**Comment by victaphu** [comment]
Note: additional improvement requirement
When user loads the transactions screen a query is made to the contract verification service to check if this address is a contract and if so, to get the verified contract code.

This has caused resource exhausted errors as many users start to use the platform (issue from firebase). 

Use tables to verify the address before querying the verification service; and only query when the user clicks the contracts tab.
