### ISSUE TITLE
support account labelling function on explorer

### ISSUE THREAD

**Issue by LeoHChen** [harmony-one/explorer-v2-frontend#157]
similar to the etherscan, some official smart contracts can be labeled as verified and given an official name, such as staking contract, DFK LP, etc, so that when users check their transactions on explorer, they would understand the interaction or approval was on the right smart contract.

**Comment by MaxMustermann2** [comment]
For the staking precompile, it will make sense to decode the input data into the requested parameters so that people can review. This can be done by parsing the 4-byte signature (which we already do using [4byte.directory](https://4byte.directory)) but I don't see it working fully for this precompile yet. Next, we can find and parse the parameters (`address`, `address`, `uint256` for Delegate and Undelegate, just `address` for CollectRewards) to display them in the UI.

**Comment by ArtemKolodko** [comment]
We can create mapped json file on client side, each community member will be able to suggest updates or add data

**Comment by ArtemKolodko** [comment]
Refactored address aliases map, data stored in JSON file; added description field
Added TOP 20 validator addresses by staking amount  (https://staking.harmony.one/validators/mainnet)
Added Gnosis safe Master copy and Proxy Factory addresses
Added KuCoin address, Binance Gateway address
