### ISSUE TITLE
read as proxy feature for contract interaction

### ISSUE THREAD

**Issue by gupadhyaya** [harmony-one/explorer-v2-frontend#71]
some contracts are deployed as proxies and there is a way to read/write via proxy to interact with such contracts in etherscan. we need this feature in our explorer. for example: https://etherscan.io/address/0x6a39909e805a3eadd2b61fff61147796ca6abb47#readProxyContract
<img width="1413" alt="Screen Shot 2021-10-13 at 12 34 23 PM" src="https://user-images.githubusercontent.com/13854340/137201301-e68a1d30-692e-4f29-8c50-1ab2d98a1cb8.png">

**Comment by victaphu** [comment]
Tutorials for proxy verification:
https://victa-kwok-wai-phu.gitbook.io/harmony-contract-verification-service/

Proxy support
Transparent: https://explorer.harmony.one/address/0xF7C2788E840BBAd8F9f852e33bFEAa91ffC49216?activeTab=7
UUPS Proxy: https://explorer.harmony.one/address/0x9CDaaBAA3b2390C3a84004707131B3e1AC7e2197?activeTab=7
Beacon Proxy: https://explorer.harmony.one/address/0xB7b9CAb3B5ABd9ac543348f93a640eeEFb0047F4?activeTab=7

This has been fixed with two PRs;
https://github.com/harmony-one/contract-verification-service/pull/9
https://github.com/harmony-one/explorer-v2-frontend/pull/125

Please confirm fixed and close this

**Comment by victaphu** [comment]
Closing this, feel free to open a new ticket if this still persists.
